# Generated by Django 5.0.14 on 2025-10-25 14:18

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('operations', 'العمليات - Operations'), ('technical', 'الفني - Technical'), ('marketing', 'التسويق - Marketing'), ('finance', 'المالية - Finance'), ('hr', 'الموارد البشرية - HR'), ('customer_services', 'خدمة العملاء - Customer Services'), ('maintenance', 'الصيانة - Maintenance'), ('security', 'الأمن - Security'), ('tenant', 'المستأجر - Tenant')], max_length=100, unique=True, verbose_name='اسم القسم')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'القسم',
                'verbose_name_plural': 'الأقسام',
                'db_table': 'accounts_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'. حتى 15 رقم مسموح.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف')),
                ('mobile', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="رقم الهاتف يجب أن يكون بالصيغة: '+999999999'. حتى 15 رقم مسموح.", regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الجوال')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسمى الوظيفي')),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الموظف')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/', verbose_name='صورة الملف الشخصي')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('preferred_language', models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2, verbose_name='اللغة المفضلة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'المستخدم',
                'verbose_name_plural': 'المستخدمون',
                'db_table': 'accounts_customuser',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_id', models.CharField(max_length=50, unique=True, verbose_name='رقم المستأجر')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة')),
                ('unit_number', models.CharField(max_length=50, verbose_name='رقم الوحدة')),
                ('floor_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الطابق')),
                ('building_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المبنى')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='رقم العقد')),
                ('contract_start_date', models.DateField(verbose_name='تاريخ بداية العقد')),
                ('contract_end_date', models.DateField(verbose_name='تاريخ نهاية العقد')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم جهة الاتصال للطوارئ')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=17, null=True, verbose_name='هاتف جهة الاتصال للطوارئ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_profile', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'ملف المستأجر',
                'verbose_name_plural': 'ملفات المستأجرين',
                'db_table': 'accounts_tenantprofile',
                'ordering': ['-created_at'],
            },
        ),
    ]
