# Generated by Django 5.0.14 on 2025-10-26 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('permits', 'التصاريح - Permits'), ('maintenance', 'الصيانة - Maintenance'), ('complaints', 'الشكاوى - Complaints'), ('marketing', 'التسويق - Marketing'), ('hr', 'الموارد البشرية - HR'), ('finance', 'المالية - Finance')], max_length=50, verbose_name='المديول')),
                ('permissions', models.JSONField(default=list, help_text='قائمة الصلاحيات: view, add, change, delete, export, approve', verbose_name='الصلاحيات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_permissions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'صلاحية القسم',
                'verbose_name_plural': 'صلاحيات الأقسام',
                'db_table': 'accounts_department_permission',
                'ordering': ['user', 'module'],
                'unique_together': {('user', 'module')},
            },
        ),
    ]
