# Generated by Django 5.0.14 on 2025-10-25 16:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('invoice_type', models.CharField(choices=[('sales', 'مبيعات'), ('purchase', 'مشتريات'), ('service', 'خدمة'), ('rental', 'إيجار'), ('penalty', 'غرامة')], max_length=20, verbose_name='نوع الفاتورة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المجموع الفرعي')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='%', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='نسبة الضريبة')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مبلغ الضريبة')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='مبلغ الخصم')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد الانتظار'), ('paid', 'مدفوعة'), ('partially_paid', 'مدفوعة جزئياً'), ('overdue', 'متأخرة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL, verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'db_table': 'finance_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='سعر الوحدة')),
                ('total', models.DecimalField(decimal_places=2, help_text='USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='المجموع')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'بند الفاتورة',
                'verbose_name_plural': 'بنود الفاتورة',
                'db_table': 'finance_invoiceitem',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الدفعة')),
                ('amount', models.DecimalField(decimal_places=2, help_text='USD', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('credit_card', 'بطاقة ائتمان'), ('debit_card', 'بطاقة خصم'), ('bank_transfer', 'تحويل بنكي'), ('cheque', 'شيك'), ('online', 'دفع إلكتروني')], max_length=20, verbose_name='طريقة الدفع')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'db_table': 'finance_payment',
                'ordering': ['-payment_date'],
            },
        ),
    ]
