# Generated by Django 5.0.14 on 2025-10-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_ar', models.CharField(default='اسم الشركة', max_length=200, verbose_name='اسم الشركة (عربي)')),
                ('company_name_en', models.CharField(default='Company Name', max_length=200, verbose_name='اسم الشركة (إنجليزي)')),
                ('logo', models.ImageField(blank=True, help_text='يفضل أن يكون بحجم 200x80 بكسل', null=True, upload_to='invoice_settings/', verbose_name='شعار الشركة')),
                ('address_ar', models.TextField(blank=True, default='', verbose_name='العنوان (عربي)')),
                ('address_en', models.TextField(blank=True, default='', verbose_name='العنوان (إنجليزي)')),
                ('phone', models.CharField(blank=True, default='', max_length=50, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('website', models.URLField(blank=True, default='', verbose_name='الموقع الإلكتروني')),
                ('tax_number', models.CharField(blank=True, default='', max_length=100, verbose_name='الرقم الضريبي')),
                ('commercial_register', models.CharField(blank=True, default='', max_length=100, verbose_name='السجل التجاري')),
                ('primary_color', models.CharField(default='#667eea', help_text='مثال: #667eea', max_length=7, verbose_name='اللون الأساسي')),
                ('secondary_color', models.CharField(default='#764ba2', help_text='مثال: #764ba2', max_length=7, verbose_name='اللون الثانوي')),
                ('footer_text_ar', models.TextField(blank=True, default='شكراً لتعاملكم معنا', verbose_name='نص التذييل (عربي)')),
                ('footer_text_en', models.TextField(blank=True, default='Thank you for your business', verbose_name='نص التذييل (إنجليزي)')),
                ('terms_ar', models.TextField(blank=True, default='', verbose_name='الشروط والأحكام (عربي)')),
                ('terms_en', models.TextField(blank=True, default='', verbose_name='الشروط والأحكام (إنجليزي)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الفاتورة',
                'verbose_name_plural': 'إعدادات الفاتورة',
            },
        ),
    ]
