# Generated by Django 5.0.14 on 2025-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_type',
            field=models.CharField(choices=[('complaint', 'شكوى'), ('complement', 'مجاملة'), ('suggestion', 'اقتراح')], max_length=20, verbose_name='نوع الحالة'),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية')], default='medium', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('in_review', 'قيد المراجعة'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة'),
        ),
    ]
