# Generated by Django 5.0.14 on 2025-10-25 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name_ar', models.CharField(default='نظام CRM', max_length=100, verbose_name='اسم الموقع (عربي)')),
                ('site_name_en', models.CharField(default='CRM System', max_length=100, verbose_name='اسم الموقع (إنجليزي)')),
                ('logo_ar', models.ImageField(blank=True, help_text='شعار النظام للعربية - PNG, JPG, JPEG, SVG', null=True, upload_to='system/logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='شعار النظام (عربي)')),
                ('logo_en', models.ImageField(blank=True, help_text='شعار النظام للإنجليزية - PNG, JPG, JPEG, SVG', null=True, upload_to='system/logos/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'svg'])], verbose_name='شعار النظام (إنجليزي)')),
                ('login_background_image', models.ImageField(blank=True, help_text='صورة خلفية شاشة تسجيل الدخول - PNG, JPG, JPEG', null=True, upload_to='system/backgrounds/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='صورة خلفية تسجيل الدخول')),
                ('login_background_color', models.CharField(default='#0d6efd', help_text='لون الخلفية (Hex Color) - يُستخدم إذا لم تكن هناك صورة', max_length=7, verbose_name='لون خلفية تسجيل الدخول')),
                ('use_background_image', models.BooleanField(default=True, help_text='استخدام صورة الخلفية بدلاً من اللون', verbose_name='استخدام صورة الخلفية')),
                ('login_page_title_ar', models.CharField(default='مرحباً بك', max_length=200, verbose_name='عنوان صفحة الدخول (عربي)')),
                ('login_page_title_en', models.CharField(default='Welcome', max_length=200, verbose_name='عنوان صفحة الدخول (إنجليزي)')),
                ('login_page_subtitle_ar', models.TextField(default='الرجاء تسجيل الدخول للمتابعة', verbose_name='عنوان فرعي (عربي)')),
                ('login_page_subtitle_en', models.TextField(default='Please login to continue', verbose_name='عنوان فرعي (إنجليزي)')),
                ('footer_text_ar', models.CharField(default='جميع الحقوق محفوظة © 2025', max_length=200, verbose_name='نص الفوتر (عربي)')),
                ('footer_text_en', models.CharField(default='All Rights Reserved © 2025', max_length=200, verbose_name='نص الفوتر (إنجليزي)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
                'db_table': 'core_system_settings',
            },
        ),
    ]
