# Generated by Django 5.0.14 on 2025-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('SAR', 'Saudi Riyal (﷼)'), ('AED', 'UAE Dirham (د.إ)')], default='USD', help_text='العملة المستخدمة في جميع أنحاء النظام - Currency symbol always in English', max_length=3, verbose_name='العملة'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='currency_symbol',
            field=models.CharField(default='$', help_text='Currency symbol (e.g., $, €, £) - Always in English', max_length=5, verbose_name='رمز العملة'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='date_format',
            field=models.CharField(choices=[('en', 'English (MM/DD/YYYY)'), ('en-gb', 'English UK (DD/MM/YYYY)'), ('iso', 'ISO (YYYY-MM-DD)')], default='en', help_text='Date format - Always Gregorian calendar in English', max_length=10, verbose_name='تنسيق التاريخ'),
        ),
    ]
