# Generated by Django 5.0.14 on 2025-10-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_systemsettings_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('SAR', 'Saudi Riyal (﷼)'), ('AED', 'UAE Dirham (د.إ)'), ('EGP', 'Egyptian Pound (E£)'), ('KWD', 'Kuwaiti Dinar (د.ك)'), ('QAR', 'Qatari Riyal (ر.ق)'), ('OMR', 'Omani Rial (ر.ع)'), ('BHD', 'Bahraini Dinar (د.ب)'), ('JOD', 'Jordanian Dinar (د.أ)')], default='EGP', help_text='العملة المستخدمة في جميع أنحاء النظام - Currency symbol always in English', max_length=3, verbose_name='العملة'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='currency_symbol',
            field=models.CharField(default='E£', help_text='Currency symbol (e.g., $, €, £, E£) - Always in English', max_length=10, verbose_name='رمز العملة'),
        ),
    ]
