# Generated by Django 5.0.14 on 2025-10-25 14:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التذكرة')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('category', models.CharField(choices=[('electrical', 'كهرباء - Electrical'), ('plumbing', 'سباكة - Plumbing'), ('hvac', 'تكييف - HVAC'), ('carpentry', 'نجارة - Carpentry'), ('painting', 'دهان - Painting'), ('cleaning', 'نظافة - Cleaning'), ('other', 'أخرى - Other')], max_length=20, verbose_name='الفئة')),
                ('priority', models.CharField(choices=[('low', 'منخفضة - Low'), ('medium', 'متوسطة - Medium'), ('high', 'عالية - High'), ('urgent', 'عاجلة - Urgent')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('open', 'مفتوحة - Open'), ('in_progress', 'قيد التنفيذ - In Progress'), ('pending', 'معلقة - Pending'), ('resolved', 'محلولة - Resolved'), ('closed', 'مغلقة - Closed')], default='open', max_length=20, verbose_name='الحالة')),
                ('unit_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الوحدة')),
                ('floor_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الطابق')),
                ('building_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم المبنى')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('resolution_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'تذكرة الصيانة',
                'verbose_name_plural': 'تذاكر الصيانة',
                'db_table': 'maintenance_ticket',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='maintenance/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='الملف')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='maintenance.ticket', verbose_name='التذكرة')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق التذكرة',
                'verbose_name_plural': 'مرفقات التذاكر',
                'db_table': 'maintenance_attachment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('is_internal', models.BooleanField(default=False, verbose_name='تعليق داخلي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='maintenance.ticket', verbose_name='التذكرة')),
            ],
            options={
                'verbose_name': 'تعليق التذكرة',
                'verbose_name_plural': 'تعليقات التذاكر',
                'db_table': 'maintenance_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_number'], name='maintenance_ticket__1a6ede_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='maintenance_status_2c3b1c_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['priority'], name='maintenance_priorit_fef7f2_idx'),
        ),
    ]
