# Generated by Django 5.0.14 on 2025-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('electrical', 'كهرباء'), ('plumbing', 'سباكة'), ('hvac', 'تكييف'), ('carpentry', 'نجارة'), ('painting', 'دهان'), ('cleaning', 'نظافة'), ('other', 'أخرى')], max_length=20, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'عالية'), ('urgent', 'عاجلة')], default='medium', max_length=10, verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد التنفيذ'), ('pending', 'معلقة'), ('resolved', 'محلولة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة'),
        ),
    ]
