# Generated by Django 5.0.14 on 2025-10-25 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفعالية')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('event_type', models.CharField(choices=[('activation', 'تفعيل - Activation'), ('campaign', 'حملة - Campaign'), ('promotion', 'عرض ترويجي - Promotion'), ('exhibition', 'معرض - Exhibition'), ('other', 'أخرى - Other')], max_length=20, verbose_name='نوع الفعالية')),
                ('status', models.CharField(choices=[('planned', 'مخطط - Planned'), ('active', 'نشط - Active'), ('completed', 'مكتمل - Completed'), ('cancelled', 'ملغي - Cancelled')], default='planned', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='الموقع')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الميزانية')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_events', to=settings.AUTH_USER_MODEL, verbose_name='الشخص المسؤول')),
            ],
            options={
                'verbose_name': 'الفعالية التسويقية',
                'verbose_name_plural': 'الفعاليات التسويقية',
                'db_table': 'marketing_event',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التفعيل')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('activation_date', models.DateField(verbose_name='تاريخ التفعيل')),
                ('participants_count', models.IntegerField(default=0, verbose_name='عدد المشاركين')),
                ('success_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='نسبة النجاح %')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='marketing.event', verbose_name='الفعالية')),
            ],
            options={
                'verbose_name': 'التفعيل',
                'verbose_name_plural': 'التفعيلات',
                'db_table': 'marketing_activation',
                'ordering': ['-activation_date'],
            },
        ),
    ]
