# Generated by Django 5.0.14 on 2025-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('activation', 'تفعيل'), ('campaign', 'حملة'), ('promotion', 'عرض ترويجي'), ('exhibition', 'معرض'), ('seminar', 'ندوة'), ('workshop', 'ورشة عمل'), ('conference', 'مؤتمر'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الفعالية'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'مخطط'), ('active', 'نشط'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='planned', max_length=20, verbose_name='الحالة'),
        ),
    ]
