# Generated by Django 5.0.14 on 2025-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'سنوية'), ('sick', 'مرضية'), ('emergency', 'طارئة'), ('unpaid', 'بدون راتب'), ('maternity', 'أمومة'), ('paternity', 'أبوة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
