# Generated by Django 5.0.14 on 2025-10-25 14:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Permit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permit_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التصريح')),
                ('permit_type', models.CharField(choices=[('goods', 'بضائع - Goods'), ('maintenance', 'صيانة - Maintenance'), ('marketing', 'تسويق - Marketing'), ('visitor', 'زائر - Visitor'), ('vehicle', 'مركبة - Vehicle'), ('other', 'أخرى - Other')], max_length=20, verbose_name='نوع التصريح')),
                ('direction', models.CharField(choices=[('send', 'إرسال - Send'), ('receive', 'استقبال - Receive')], max_length=10, verbose_name='الاتجاه')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='الشخص المسؤول')),
                ('contact_phone', models.CharField(blank=True, max_length=17, null=True, verbose_name='هاتف الاتصال')),
                ('requested_date', models.DateField(verbose_name='تاريخ الطلب')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار - Pending'), ('approved', 'موافق عليه - Approved'), ('rejected', 'مرفوض - Rejected'), ('cancelled', 'ملغي - Cancelled')], default='pending', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permits', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permits', to=settings.AUTH_USER_MODEL, verbose_name='المستأجر')),
            ],
            options={
                'verbose_name': 'التصريح',
                'verbose_name_plural': 'التصاريح',
                'db_table': 'permits_permit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'موافق - Approved'), ('rejected', 'مرفوض - Rejected'), ('redirected', 'محول - Redirected')], max_length=20, verbose_name='الإجراء')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='التعليقات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('approver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permit_approvals', to=settings.AUTH_USER_MODEL, verbose_name='الموافق')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='permits.permit', verbose_name='التصريح')),
                ('redirected_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirected_permits', to=settings.AUTH_USER_MODEL, verbose_name='محول إلى')),
            ],
            options={
                'verbose_name': 'موافقة التصريح',
                'verbose_name_plural': 'موافقات التصاريح',
                'db_table': 'permits_approval',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PermitAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='permits/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='الملف')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_size', models.IntegerField(verbose_name='حجم الملف (بايت)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='permits.permit', verbose_name='التصريح')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق التصريح',
                'verbose_name_plural': 'مرفقات التصاريح',
                'db_table': 'permits_attachment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['permit_number'], name='permits_per_permit__7c6336_idx'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['status'], name='permits_per_status_6c419b_idx'),
        ),
        migrations.AddIndex(
            model_name='permit',
            index=models.Index(fields=['tenant'], name='permits_per_tenant__c34f08_idx'),
        ),
    ]
