# Generated by Django 5.0.14 on 2025-10-25 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permit',
            name='direction',
            field=models.CharField(choices=[('send', 'إرسال'), ('receive', 'استقبال')], max_length=10, verbose_name='الاتجاه'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='permit_type',
            field=models.CharField(choices=[('goods', 'بضائع'), ('maintenance', 'صيانة'), ('marketing', 'تسويق'), ('visitor', 'زائر'), ('vehicle', 'مركبة'), ('other', 'أخرى')], max_length=20, verbose_name='نوع التصريح'),
        ),
        migrations.AlterField(
            model_name='permit',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
    ]
