# Generated by Django 5.0.14 on 2025-10-26 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permits', '0002_alter_permit_direction_alter_permit_permit_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم سير العمل')),
                ('permit_type', models.CharField(blank=True, choices=[('goods', 'بضائع'), ('maintenance', 'صيانة'), ('marketing', 'تسويق'), ('visitor', 'زائر'), ('vehicle', 'مركبة'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='نوع التصريح')),
                ('deadline_hours', models.IntegerField(default=24, verbose_name='المهلة الزمنية (ساعات)')),
                ('auto_redirect', models.BooleanField(default=True, verbose_name='تحويل تلقائي عند تجاوز المهلة')),
                ('notify_admin', models.BooleanField(default=True, verbose_name='إشعار المدير عند التحويل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن الموافقة')),
                ('backup_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_workflows', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول البديل')),
            ],
            options={
                'verbose_name': 'سير عمل الموافقة',
                'verbose_name_plural': 'سير عمل الموافقات',
                'db_table': 'permits_approval_workflow',
                'ordering': ['permit_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PendingApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(verbose_name='الموعد النهائي')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='متأخر')),
                ('redirected', models.BooleanField(default=False, verbose_name='تم التحويل')),
                ('redirected_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحويل')),
                ('admin_notified', models.BooleanField(default=False, verbose_name='تم إشعار المدير')),
                ('completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('permit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to='permits.permit', verbose_name='التصريح')),
                ('redirected_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirected_approvals', to=settings.AUTH_USER_MODEL, verbose_name='محول إلى')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_approvals', to='permits.approvalworkflow', verbose_name='سير العمل')),
            ],
            options={
                'verbose_name': 'موافقة معلقة',
                'verbose_name_plural': 'موافقات معلقة',
                'db_table': 'permits_pending_approval',
                'ordering': ['deadline', '-created_at'],
            },
        ),
    ]
